name: panbrowser

channels:
  - conda-forge
#  - bioconda
  - anaconda
  - defaults

dependencies:
  - python=3.8
  - numpy=1.19.2
  - pandas=1.1.3
  - flask-sqlalchemy=2.5.1
  - passlib=1.7.4
  - pymysql=0.10.1
  - flask-mail=0.9.1=py_2


